exclude: '^$'
fail_fast: false
repos:
-   repo: local
    hooks:
      - id: isort
        args:
            - --check-only
            - -rc
            - src/
            - tests/
        name: isort
        entry: isort
        language: system
        types: [python]

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: flake8
        exclude: docs/
        args:
        - src/
        - tests/
    -   id: check-merge-conflict
