language: python
sudo: false
python:
  - 3.6


cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1


install:
  - pip install tox "coverage<=4.0" codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
