# Generated by Django 2.1.1 on 2018-09-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'get_latest_by': 'id', 'ordering': ('timestamp', 'id')},
        ),
        migrations.AlterField(
            model_name='record',
            name='logger',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
